export const FETCH_USERS_PROGRESS = 'FETCH_USERS_PROGRESS';
export const FETCH_USERS_FINISHED = 'FETCH_USERS_FINISHED';

export const FETCH_PROJECTS_PROGRESS = 'FETCH_PROJECTS_PROGRESS';
export const FETCH_PROJECTS_FINISHED = 'FETCH_PROJECTS_FINISHED';

export const LOGIN_PROGRESS = 'LOGIN_PROGRESS';
export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const LOGOUT_PROGRESS = 'LOGIN_PROGRESS';
export const LOGOUT_FINISHED = 'LOGIN_FINISHED';

export const FETCH_INFO_PROGRESS = 'FETCH_INFO_PROGRESS';
export const FETCH_INFO_FINISHED = 'FETCH_INFO_FINISHED';


export const UNAUTHORIZED = "UNAUTHORIZED";
